# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15bf23401ffa2a43c9c031a5f83411d0bbe19f7bb86a6aa79dd357ad08655d644b73bf9e2241c35ac3122ad21d0a296d92ad7f4eeb47db5ba99ba66570b245e8

test:
  secret_key_base: 15687530b6730adbefe2112acb3ce4d8fa037c4b1b830d64b284cf7b8e75a8d365efe4f5c6883de2e61ae0457b26697107b967ad21d05d6fba1159ce1554ba64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
